// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BUiD1Bl3nGuq6wBMUKJTUak2xg_8shU',
    appId: '1:915992683905:web:e1a72c6a578881a9c37480',
    messagingSenderId: '915992683905',
    projectId: 'webrtc-demo-e3685',
    authDomain: 'webrtc-demo-e3685.firebaseapp.com',
    storageBucket: 'webrtc-demo-e3685.appspot.com',
    measurementId: 'G-8QETVW8E62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG7SNHpn2-YmLoiiSHMdJmh0CURTHfRFQ',
    appId: '1:915992683905:android:8c44c8d63d9c239ac37480',
    messagingSenderId: '915992683905',
    projectId: 'webrtc-demo-e3685',
    storageBucket: 'webrtc-demo-e3685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWKpDCFerNiFhfiTSSsszS8wFzLUi6daI',
    appId: '1:915992683905:ios:70bca16f5dab3131c37480',
    messagingSenderId: '915992683905',
    projectId: 'webrtc-demo-e3685',
    storageBucket: 'webrtc-demo-e3685.appspot.com',
    iosBundleId: 'com.example.webrtcDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWKpDCFerNiFhfiTSSsszS8wFzLUi6daI',
    appId: '1:915992683905:ios:eece8af0bccda3cfc37480',
    messagingSenderId: '915992683905',
    projectId: 'webrtc-demo-e3685',
    storageBucket: 'webrtc-demo-e3685.appspot.com',
    iosBundleId: 'com.example.webrtcDemo.RunnerTests',
  );
}
